[common]
# these are /48 allocations
ula = "fda2:d982:1da2"
gua = "2001:470:b1bb"
# this is a /16
v4 = "10.77.0.0"

# fake machines that use netstack
[hosts.httpserver]
network = "fake"
# cloud machines
[hosts.droplet]
network = "cloud"
ip_addr = "139.59.35.172"
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGgsdWLA9lAxG7PTARO6X02ZJCwqPT2eMBEtGI30J/MA root@nixos.qcow2.gz-s-4vcpu-8gb-intel-blr1-01"
